version: '3'
services:
    db:
        image: postgres:16
        volumes:
            - ./db/postgres:/var/lib/postgresql/data/
        ports:
            - 5434:5432
        env_file:
            - .env

    redis:
        volumes:
            - ./db/redis:/data
        image: redis:7-alpine

    backend:
        restart: always
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8001:8000
        env_file:
            - .env
        volumes:
            - ./app:/app
        depends_on:
            - db
            - redis
 
    celery:
        build:
            context: .
        command: celery -A main worker --loglevel=ERROR
        volumes:
            - ./app:/app
        depends_on:
            - backend
            - redis

    celery-beat:
        build:
            context: .
        command: celery -A main beat --loglevel=ERROR
        volumes:
            - ./app:/app
        depends_on:
            - celery

    flower:
        build:
            context: .
        volumes:
            - ./app:/app
        ports:
            - "5555:5555"
        command: sh -c "sleep 2 && celery -A main flower"
        depends_on:
            - celery
            - celery-beat
